"""Pre-compute a full demo run into frontend/public/snapshot.json.

The static GitHub Pages preview has no backend, so every API response the app
needs is captured here once, at build time. The script runs the real FastAPI
app in demo mode against a throwaway SQLite database, so the snapshot is
literally what the API returns rather than a hand-written fixture.

No network and no API keys: DEMO_MODE serves recorded pages from
data/demo_sites.json, and ANTHROPIC_API_KEY is removed from the environment so
briefs come from the deterministic template.

Usage:  python scripts/build_snapshot.py
"""
import asyncio
import json
import os
import shutil
import sys
import tempfile
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "frontend" / "public" / "snapshot.json"

# The environment has to be set before app.db is imported, because it resolves
# DATABASE_URL at import time.
_tmp = tempfile.mkdtemp(prefix="dealsieve-snapshot-")
os.environ["DEMO_MODE"] = "true"
os.environ["DATABASE_URL"] = f"sqlite:///{_tmp}/snapshot.db"
os.environ.pop("ANTHROPIC_API_KEY", None)   # force the template brief
os.environ.pop("SEED_DEMO", None)           # we import explicitly below
sys.path.insert(0, str(ROOT / "backend"))

from fastapi.testclient import TestClient          # noqa: E402
from sqlalchemy import select                      # noqa: E402

from app.db import Base, SessionLocal, engine      # noqa: E402
from app.main import app, run_enrichment           # noqa: E402
from app.models import Job, Lead                   # noqa: E402


def build() -> dict:
    Base.metadata.create_all(bind=engine)
    client = TestClient(app)

    report = client.post("/api/leads/import-sample").json()
    print(f"  imported {report['added']} leads from {report['rows_read']} rows")

    # Enrichment is driven directly rather than through /api/enrich, so the
    # script can await it instead of polling a background task.
    with SessionLocal() as db:
        ids = list(db.scalars(select(Lead.id)).all())
        db.add(Job(id="snapshot", total=len(ids), status="running"))
        db.commit()
    asyncio.run(run_enrichment("snapshot", ids))

    stats = client.get("/api/stats").json()
    print(f"  enriched {stats['enriched']}, failed {stats['failed']} (expected: some demo sites are unreachable by design)")

    leads = client.get("/api/leads", params={"sort": "score", "order": "desc"}).json()["items"]

    details, briefs = {}, 0
    for item in leads:
        brief = client.post(f"/api/leads/{item['id']}/brief").json()
        assert brief["source"] == "template", f"expected a template brief, got {brief['source']}"
        briefs += 1
        details[str(item["id"])] = client.get(f"/api/leads/{item['id']}").json()
    print(f"  generated {briefs} template briefs")

    # The industry filter matches the raw column, not the industry guessed from
    # the website, so the raw value is kept to kept filtering faithful offline.
    with SessionLocal() as db:
        raw_industries = {str(l.id): l.industry for l in db.scalars(select(Lead)).all()}

    return {
        "generated_at": datetime.now(timezone.utc).isoformat(timespec="seconds"),
        "note": "Pre-computed demo run. Generated by scripts/build_snapshot.py; do not edit by hand.",
        "stats": stats,
        "settings": client.get("/api/settings").json(),
        "leads": leads,
        "details": details,
        "raw_industries": raw_industries,
    }


def main() -> int:
    print("Building static snapshot...")
    try:
        snapshot = build()
    finally:
        engine.dispose()
        shutil.rmtree(_tmp, ignore_errors=True)

    scored = [l for l in snapshot["leads"] if l["score"] is not None]
    assert len(snapshot["leads"]) == 13, f"expected 13 leads, got {len(snapshot['leads'])}"
    assert len(scored) == 13, f"expected every lead scored, got {len(scored)}"
    assert len(snapshot["details"]) == 13
    assert all(d.get("brief") for d in snapshot["details"].values()), "a lead is missing its brief"

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(json.dumps(snapshot, indent=1, sort_keys=True) + "\n")
    print(f"Wrote {OUT.relative_to(ROOT)} ({OUT.stat().st_size / 1024:.0f} KB, {len(snapshot['leads'])} leads)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
